name: PayCore QA/CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  automatized-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: paycore
        ports:
          - 5432:5432
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Java Config
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Run Tests (JUnit)
        run: ./gradlew test

      - name: Final Report
        run: echo "All tests passed. The Back-end is already!"
